---
title: "Code-along, Week 03: Paralympics"
author: "Alex Homer"
date: "7 October 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r load-packages, message = FALSE}
library(tidyverse)
```

## Read data
The primary data are drawn from the "Tidy Tuesday" project: [2021 Week 32: Paralympics](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-08-03/readme.md) (credit: [International Paralympic Committee](https://db.ipc-services.org/sdms/hira/web/index)).  The secondary data are from the Organisation for Economic Co-operation and Development ^[OECD (2021), Population (indicator). doi: [10.1787/d434f82b-en](https://doi.org/10.1787/d434f82b-en) (Accessed on 06 October 2021)].

```{r read-data, message = FALSE}
paralympic_data <-read_csv(
  "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-03/athletes.csv"
)

oecd_data <- read_csv("data/oecd_pop.csv")
```

The rest of this document will be filled in during Thursday's live coding session.

